# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Everybody Needs a Fishbowl
logo: /assets/images/fishbowl.png
name: Travis Tomsu
email: travis.tomsu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just a regular, everyday normal guy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.travistomsu.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: travis_tomsu
github_username:  ttomsu
repository: ttomsu/ttomsu.github.io
locale: en-US
title_separator: "-"

author:
  name: Travis Tomsu
  bio: "Geek, father, skier"
  location: "New York, USA"
  avatar: "/assets/images/travis-husky.jpg"
  twitter: travis_tomsu
  github: ttomsu
  email: travis.tomsu@gmail.com

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
plugins:
- jekyll-archives
- jekyll-feed
- jekyll-include-cache
- jekyll-redirect-from
- jekyll-sitemap

search: true

tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: google-gtag
  google:
    tracking_id: "UA-64309090-1"

paginate: 5 # amount of posts to show
paginate_path: /page:num/

minimal_mistakes_skin: air

footer:
  links:
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/travis_tomsu"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/ttomsu"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- README.md
- CNAME
- favicon.xcf

og_image: /assets/images/fishbowl.png

defaults:
# _posts
- scope:
    path: ""
    type: posts
  values:
    layout: single
    classes: wide
    author_profile: true
    related: true
    share: true
# _pages
- scope:
    path: "_pages"
    type: pages
  values:
    layout: single
    author_profile: true
